"""
Здесь хранятся словари и списки для скриптов мониторинга.
"""

# словарь вариантов написания брендов
brand_variations_dict = {
                  #'ActivLab': [],
                  #'APPLIED NUTRITION': []
                  #'BCN': [],
                  'be first': ['be first1', 'befirst', 'Be first'],
                  'Beauty Fit': ['BeautyFit'],
                  'Bio Schwartz': ['bioschwartz'],
                  'BombBar': ['Bombbar Chikalab', 'Bombbar (Бомббар)', 'Бомббар "BOMBBAR"', 'Bombbar', 'Bombbar.', 'BomBar', 'Бомббар'],
                  'Bounty': ['Баунти'],
                  'BSN': ['BSN Amino X'],
                  'Bulk Supplements': ['Bulk'],
                  'California Gold Nutrition': ['California Gold Nutrition iHerb', 'California Gold Nutrition USA',
                                                'California Gold жидкий витамин D3 для детей', 'California Gold Омега-3 с витамином D3 для детей', 'Iherb California Gold Collagen',
                                                'Калифорния Голд Нутришн', 'California Gold', 'California', 'Калифорния'],
                  'Carlson Labs': ['Carlson Labs D3 детский', 'Carlson'],
                  'FIT KIT': ['FITKIT', 'fitkit', 'fit kit'],
                  'CHIKALAB': ['CHIKALAB.', 'CHIKA LAB', 'chikalab', 'chika lab', 'Chikabar', 'chikabar'],
                  #'GEL4U': [],
                  'IronMan': ['Iron Man-QB', 'Iron Man.', 'Iron Man'],
                  #'Isopure': [],
                  #'Lactoflorene': [],
                  'Lake Avenue Nutrition': ['ASL/ Lake Avenue Nutrition', 'Lake Avenue'],
                  "M&M's": ["M&M's United Kingdom", "M&Ms Europe", "M&Ms", "M&M,s"],
                  'Mars': ['Mars United Kingdom', 'Mars protein', 'Mars Hi Protein bars', 'Mars Incorporated', 'Mars Chocolate Drinks & Treats', 'Mars Inc.'],
                  'MAXLER': ['Maxler EU', 'Maxler USA', 'MAXLER Аминокислоты 100% Pure Glutamine, Maxler', 'MaxlerGamine', 'Maxler Acetyl l-Carnitine', 'Maxler Zinc Picolinate',
                             'Maxler Omega-3 Gold', 'Протеин Maxler 100% Golden Whey Шоколад', 'Maxler Creatine Nari', 'HOT/ Сывороточный протеин Maxler 100%'],
                  'MD': ['MD.', 'MD-QB'],
                  'Milky Way': ['MilkyWay', 'MilkyWay United Kingdom', 'Milky Way USA', 'Milky way chocopasta'],
                  #'Multipower': [],
                  #'MUSCLETECH': [],
                  'MyProtein': ['My Protein'],
                  #'Natrol': [],
                  #'Novo': [],
                  'NOW': ['NOW FOODS', 'SuperNOW', 'NOW / NOW FOODS', 'NOW FOODS / NOW', 'NOWFOODS', 'NOW Foods, NOW', 'NOW FOOD', 'NOW FOODS/НАУ ФУДС', 'NOW/NOW FOODS',
                          'NOW Omega 3', 'NOW Foods, жирные кислоты омега-3, 200 капсул', 'NOW Foods GABA 750 мг 100 капсул', 'NOW FOODS iHerb', 'NOW FOODS ДУБЛЬ', 'now sports',
                          'НАУ', 'Now Витамин Д3 5000 120 капсул', 'Рыбий жир и омега Now Foods 500ЭПК/250ГК'],
                  'NUTREX': ['Nutrex research', 'Nutrex BCAA DRIVE Аминокислоты 200 таблеток', 'Nutrex (USA)', 'nutrex', 'Nutrex Hawaii'],
                  'Olimp Sport Nutrition': ['Olimp'],
                  #'OstroVit': [],
                  #'PhD': [],
                  #'Power System': [],
                  #'Protego': [],
                  #'Real Pharm': [],
                  'Science in sports (SIS)': ['Science in Sport (SIS)', 'SIS (Science in Sport)', 'Sis', 'Science in Sports', 'Science in sport', 'SIS'],
                  'SFD': ['SFD Nutrition'],
                  #'SmartLife': [],
                  #'Snaq Fabriq': [],
                  'Snickers': ['Snickers шоколадный батончик молочный, нуга', 'Snickers СНИКЕРС', 'Сникерс,Snickers', 'Snickers/ Шоколадный батончик/ молочный шоколад',
                               'Шоколад Snickers', 'Snickers шоколадный батончик молочный', 'Сникерс'],
                  'SOLGAR': ['SOLGAR СОЛГАР', 'SOLGAR 1947', 'SOLGAR витамины', 'SOLGAR/СОЛГАР бета-каротин', 'SOLGAR. Омега -3. 50 капсул', 'SOLGAR/Солгар',
                             'SOLGAR/Солгар для женщин', 'Солгар Solgar', 'Solgar Inc', 'СОЛГАР ВИТАМИНЫ', 'Solgar', 'Солгар', 'СОЛГАР'],
                  #'Sporty': [],
                  'Swanson': ['Swanson (USA)'],
                  #'The Gummies Co': [],
                  #'UNS': [],
                  'USPLabs': ['USP Labs'],
                  #'V-Shape Supps': [],
                  #'VITUAL LABORATORIES': [],
                  'Warrior Crunch': ['Warrior'],
                  #'WOW ENERGY': [],
                  'XXI Power': ['XXIPower'],
                  'YAMAMOTO': ['Yamamoto Kanpo', 'Yamamoto Nutrition']
                }

# списки, использующиеся в текстовых фильтрах
name_similarity_both_true = [
    ['батонч', 'protein delice'], ['подсластитель', 'сахарозаменитель', 'заменитель сахара'],
    ['arginin', 'аргинин'], ['alanin', 'аланин'], ['alcar', 'алкар'], ['astaxanthin', 'астаксантин'], ['amino', 'амино'],
    ['bacop', 'бакоп'], ['bcaa', 'бцаа'], ['beta fuel'], ['biotin', 'биотин'], ['biscuit', 'бисквит'], ['bromelain', 'бромелаин'], ['buttercream', 'паста', 'captain peanut'],
    ['cardio', 'кардио'], ['carnitin', 'карнитин'], ['carnosin', 'карнозин'], ['casein', 'казеин'], ['cholin', 'холин'], ['chelat', 'хелат'], ['chocoron', 'меренг', 'макарун'],
    ['chips', 'чипсы'], ['citrat', 'цитрат'], ['citrullin', 'цитруллин', 'цитрулин'], ['cla ', 'cla,', 'linoleic acid', 'линолевая кислота'], ['caffein', 'кофеин'],
    ['cookie', 'печенье', 'печенья', 'chikapie', 'protein cake'], ['colostrum', 'молозив'],
    ['collagen', 'коллаген'], ['curcumin', 'куркумин', 'turmeric'], ['coq10', 'coenzyme q10', 'коэнзим q10'],
    ['d3', 'd 3', 'д3', 'д 3'], ['dmae', 'дмае'],
    ['echinac', 'эхинац'], ['electrolyt', 'электролит'], ['ener', 'энер'],
    ['fat burner', 'fatburner', 'жиросжигател'], ['fish oil', 'рыбий жир'],
    ['gaba', 'гамк'], ['gainer', 'гейнер'], ['glucosamin', 'глюкозамин', '4joints'], ['glutamin', 'глютамин', 'глутамин'], ['glutathion', 'глутатион'],
    ['grape seed', 'виноградных косточек'], ['guarana', 'гуаран'],
    ['hyaluron', 'гиалурон'], ['hmb', 'гмб'], ['htp', 'хтп', 'гидрокситриптофан', 'гидрокси триптофан'], ['huperzine', 'гуперзин'],
    ['immune 4', 'иммуне 4'], ['inulin', 'инулин'], ['isolat', 'изолят'], ['isoton', 'изотон', 'iso plus'],
    ['jam', 'джем'], ["johns wort", "john's wort", "зверобо"],
    ['folic', 'фолиев'], ['fiber', 'клетчатка'], ['k2', 'k 2', 'к2', 'к 2'],
    ['lactobif', 'лактобиф'], ['lysin', 'лизин'], ['life boost', 'лайф буст'], ['lipoic', 'липоев'], ['liposomal', 'липосомал'], ['lutein', 'лютеин'],
    ['maca', 'мака'], ['magnesi', 'магни'], ['melatonin', 'мелатонин'], ['menopaus', 'менопауз'], ['muesli', 'мюсл'],
    ['niacin', 'ниацин'], ['noni', 'нони'],
    ['olive leaf', 'оливковых листьев', 'листьев оливы'], ['omega', 'омега'], ['ornithin', 'орнитин'],
    ['pancake', 'панкейк', 'блинч'], ['picolinat', 'пиколинат'], ['porridg', 'каша', 'каши'], ['prebiotic', 'пребиотик'], ['prework', 'pre work', 'pre-work', 'предтрен'],
    ['pqq', 'pyrroloquinoline', 'пирролохинолинхинон'],
    ['sambucus', 'бузина', 'бузины'], ['sauce', 'соус'], ['selenium', 'селен'], ['spirulin', 'спирулин'], ['superfood', 'суперфуд', 'супер фуд'],
    ['testoster', 'тестостерон'], ['theanin', 'теанин'], ['thistle', 'чертополох', 'расторопша'], ['topping', 'toping', 'топпинг', 'топинг'], ['tribulus', 'трибулус'],
    ['tyrosin', 'тирозин'], ['twisted', 'твистед'],
    ['quercetin', 'кверцетин'],
    ['vegan', 'веган'],
    ['vitamin c', 'витамин ц', 'витамин с', 'витамин c'],
    ['vitamin b', 'витамин b', 'витамин б', 'витамин в', 'витамины b', 'витамины б', 'витамины в', 'витамины группы b', 'витамины группы б', 'витамины группы в'],
    ['vitamin d3', 'витамин d3', 'витамин д3', 'vitamin d-3', 'витамин d-3', 'витамин д-3', 'vitamin d 3', 'витамин d 3', 'витамин д 3'],
    ['vitamin e', 'витамин е', 'витамин e'],
    ['zma']
]

name_similarity_both_true_several_words = [
    [['батончик'], ['bombbar', 'duo'], ['energy', 'bake'], ['crunch', 'sparc']],
    [['драже'], ['в', 'шоколаде'], ['шарик']],
    [['смесь', 'морожен']],
    [['multivitamin'], ['multi', 'vitamin'], ['витамин', 'комплекс'], ['мульти', 'витамин'], ['мультивитамин'], ['поли', 'витамин'], ['поливитамин']],
    [['rapid', 'recovery'], ['напит', 'углев', 'белк'], ['гейнер', 'восстанов'], ['напит', 'восстанов']]
]

name_similarity_both_true_exact_words = [
    ['bar', 'батончик', 'батончики', 'chikabar', 'snaqer'],
    ['chocolate', 'шоколад', 'шоколадка', 'шоколада', 'chikasport'], ['creatine', 'креатин'],
    ['gel', 'гель'],
    ['iron', 'железо'],
    ['keto', 'кето'],
    ['whey', 'протеин', 'вей'],
    ['zinc', 'цинк', 'цинка']
]
